version: '3.8'

services:
  budgeting-app-db:
    container_name: budgeting-app-db-container
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  budgeting-app-cache:
    container_name: budgeting-app-redis-container
    image: redis:alpine
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
